version: '3.9'

services:
  grafana:
    image: grafana/grafana:9.4
    restart: always
    ports:
      - "127.0.0.1:9002:3000"
    networks:
      default:
      postgres:
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

networks:
  default:
  postgres:
    name: postgres_default
    external: true
