version: '3.9'

services:
  grafana:
    image: grafana/grafana:9.3.2
    restart: always
    ports:
      - "127.0.0.1:9002:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
