version: "3.9"

services:
  mariadb:
    image: mariadb:10.9
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9004:80
    environment:
        PMA_HOST: mariadb
